% Script to format French NFI in the format required by Sophia
% Georges Kunstler

# List of variables requested

##Plot level
- Plot code
- Survey date
- Department
- Plot coordinates (Latitude/Longitude) **\color{red} Coordinates of the cell so +/- 500m** 
- Is the plot protected (i.e. nature reserve) **\color{red} Not available** 
- Ownership (public/private) **\color{red} Not available**
- Altitude **\color{red} The exact elevation is not available in the public data, you can use the elevation based on cell coordinates. I purchased the exact elevation for the plot, but this can not be redistributed directly.**
- Management history
- Forest type (European forest type?)
 
## Tree
- Plot code
- Species
- Tree status (alive, dead, cut/harvested)
DEAD RECRUIT HARVESTED ALIVE
- DBH
- Height
- Sample radius
- Damage to the tree (yes/no)
NEED to check in variables list
- Coordinates of the tree in the plot (angle and distance from plot centre) **\color{red} Not available**
- Growth measurement – radial growth **\color{red} Missing for some tree**
